<?php
// $Id$

/**
 * @file
 * Administration tasks for the geo module, such as finding and adding new tables to views.
 *
 * @version $Id$
 * @package geo
 */

/**
 * Implementation of hook_menu().
 */
function geo_data_menu() {
  return array(
    'admin/content/geo' => array(
      'path'        => 'admin/build/geo',
      'title'       => t('Geospatial data'),
      'description' => t('Manage geographic information'),
      'file'        => 'geo_data.admin.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('geo_data_admin'),
      'access arguments' => array('administer geospatial data'),
    ),
  );
}

/**
 * Implementation of hook_perm()
 */
function geo_data_perm() {
  return array(t('administer geospatial data'));
}
