<?php
// $Id$

/**
 * @file
 * Administration UI for geo data, such as finding and adding new sources.
 *
 * @package geo
 */

/**
 * Implements hook_menu().
 */
function geo_ui_menu() {
  module_load_include('menu.inc', 'geo_ui', 'includes/geo_ui');
  return geo_ui_menu_menu();
}

/**
 * Implements hook_permission()
 */
function geo_ui_permission() {
  return array('administer geospatial data');
}

/**
 * Implements hook_theme().
 */
function geo_ui_theme() {
  module_load_include('theme.inc', 'geo_ui', 'theme/geo_ui');
  return geo_ui_theme_theme();
}
