<?php

/**
 * @file
 * Developer helpers for people working on the geo module
 */
 
/**
 * Implementation of hook menu
 */
function geo_devel_menu($may_cache) {
  $items = array();

  if ($may_cache) {

    $items[] = array(
      'path' => 'geo/devel/srid',
      'title' => t('SRID Generator'),
      'callback' => 'geo_devel_srid_page',
      'access' => true,
      'type' => MENU_NORMAL_ITEM,
      'discription' => t('Get a dump of the SRID table info'),
    );
  } else {
    
  }

  return $items;
}

/**
 * A page callback that takes the SRID table (in Postgis) and turns it into a useful array, that can be dumped into a .inc file
 */
function geo_devel_srid_page() {
  if (geo_backend_type() == 'postgis') {
    $options = array();
    $res = db_query("SELECT srid, srtext FROM {spatial_ref_sys} ORDER BY srid");
    while($row = db_fetch_array($res)) {
      $matches = array();
      if (preg_match('/PROJCS\["([^"]*)"/', $row['srtext'], $matches)) {
        $options[$row['srid']] = $matches[1] . ' (SRID: ' . $row['srid'] . ')';
        
      } elseif (preg_match('/GEOGCS\["([^"]*)"/', $row['srtext'], $matches)) {
        $options[$row['srid']] = $matches[1] . ' (SRID: ' . $row['srid'] . ')';
      }
    }
    return '<textarea style="width: 100%; height: 100%">' . var_export($options, TRUE) . '</textarea>';
  } else {
    return 'You are not running the PostGIS backend. You can\'t do this. :-(';
  }
}